apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8shello-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8shello-frontend
  template:
    metadata:
      labels:
        app: k8shello-frontend
    spec:
      containers:
        - name: app
          image: mehdiz/k8shello-frontend:1.0.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8shello-frontend
spec:
  selector:
    app: k8shello-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort